# Generated by Django 4.0.2 on 2022-03-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=False, max_length=1000),
            preserve_default=False,
        ),
    ]
