# Generated by Django 4.0.2 on 2022-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_contact_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('journal', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('authors', models.CharField(max_length=300)),
            ],
        ),
    ]
